USE [master]
GO

/****** Object:  Database [malawi411-final]    Script Date: 09/23/2018 13:52:15 ******/
CREATE DATABASE [malawi411-final] ON  PRIMARY 
( NAME = N'malawi411-final', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\malawi411-final.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'malawi411-final_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\malawi411-final_log.LDF' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [malawi411-final] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [malawi411-final].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [malawi411-final] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [malawi411-final] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [malawi411-final] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [malawi411-final] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [malawi411-final] SET ARITHABORT OFF 
GO

ALTER DATABASE [malawi411-final] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [malawi411-final] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [malawi411-final] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [malawi411-final] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [malawi411-final] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [malawi411-final] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [malawi411-final] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [malawi411-final] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [malawi411-final] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [malawi411-final] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [malawi411-final] SET  ENABLE_BROKER 
GO

ALTER DATABASE [malawi411-final] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [malawi411-final] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [malawi411-final] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [malawi411-final] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [malawi411-final] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [malawi411-final] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [malawi411-final] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [malawi411-final] SET  READ_WRITE 
GO

ALTER DATABASE [malawi411-final] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [malawi411-final] SET  MULTI_USER 
GO

ALTER DATABASE [malawi411-final] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [malawi411-final] SET DB_CHAINING OFF 
GO

